name: My First Workflow

on: [push, fork]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
               
            - name: List and Read files
              run: |
                echo "My First Github Actions Job"
                ls -ltra
                cat README.md
            - name: Generate ASci content
              run: -cowsay -f dragon "Run for cover, I am a DRAGON.... RAWR" >> dragon.txt
            # - name: List Files
            #   run: ls
            
            # - name: Read Files
            #   run: cat README.md